/*
 * Metal GPU acceleration for BitMamba - Pure C implementation.
 *
 * Uses the ObjC runtime C API (objc_msgSend, sel_registerName, objc_getClass)
 * to call Metal framework without Objective-C syntax or ARC.  Same approach
 * as GLFW, sokol, and other C libraries that talk to Cocoa/Metal.
 *
 * Every objc_msgSend call uses a fully typed (non-variadic) function pointer
 * cast to guarantee correct arm64 calling convention.
 *
 * Manages Metal device, command queue, compute pipelines, and buffer
 * allocation.  Targets batched prefill (bitlinear_forward_batch) only.
 */

#ifdef HAS_METAL

#include <objc/message.h>
#include <objc/runtime.h>
#include <pthread.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "bitmamba.h"
#include "bm_metal.h"
#include "dispatch.h"

/* Embedded shader source (generated by xxd at build time) */
#include "bm_shaders_source.h"

/* ── Metal types (avoids #include <Metal/Metal.h>) ───────────────── */

typedef unsigned long NSUInteger;

typedef struct {
    NSUInteger width, height, depth;
} MTLSize;

enum {
    MTL_RESOURCE_STORAGE_MODE_SHARED = 0,
    MTL_CMD_BUF_STATUS_COMPLETED = 4,
    NS_UTF8_STRING_ENCODING = 4,
    MTL_MATH_MODE_FAST = 1,
};

/* ── ObjC runtime helpers ────────────────────────────────────────── */

#define sel(name) sel_registerName(name)
#define cls(name) (void *) objc_getClass(#name)

/*
 * Typed objc_msgSend cast.  Each call site specifies the exact function
 * signature, guaranteeing correct arm64 calling convention (no variadic
 * promotion, no float-to-GPR misrouting for large structs).
 *
 * NOTE: on x86_64, struct returns >16 bytes need objc_msgSend_stret and
 * floating-point returns need objc_msgSend_fpret.  This code only targets
 * Apple Silicon (arm64), where objc_msgSend handles all return types.
 *
 * Usage: OC(return_type, (param_types))(args)
 *   OC(void*, (void*, SEL))(obj, sel("alloc"))
 *   OC(void, (void*, SEL, void*, NSUInteger, NSUInteger))(enc, s, buf, 0, 0)
 */
#if !defined(__aarch64__)
#warning \
    "OC() macro assumes arm64 objc_msgSend ABI; x86_64 may need stret/fpret"
#endif
#define OC(ret, args) ((ret(*) args) objc_msgSend)

/* ── External symbols ────────────────────────────────────────────── */

extern void *MTLCreateSystemDefaultDevice(void);
extern void *objc_autoreleasePoolPush(void);
extern void objc_autoreleasePoolPop(void *);

/* ── Memory management (replaces ARC) ────────────────────────────── */

static inline void release(void *obj)
{
    if (obj)
        OC(void, (void *, SEL))(obj, sel("release"));
}

/* Create an autoreleased NSString from a C string. */
static inline void *nsstr(const char *s)
{
    return OC(void *, (void *, SEL, const char *) )(
        cls(NSString), sel("stringWithUTF8String:"), s);
}

/* ── Metal state ─────────────────────────────────────────────────── */

/* Serializes access to scratch buffers and GPU dispatch.
 * Currently single-threaded, but guards against future multi-threading. */
static pthread_mutex_t g_metal_mutex = PTHREAD_MUTEX_INITIALIZER;

static void *g_device = NULL;
static void *g_queue = NULL;
static void *g_rms_norm_quantize_pipeline = NULL;
static void *g_bitlinear_batch_pipeline = NULL;
static void *g_residual_add_pipeline = NULL;
static bool g_metal_ready = false;

/* Zero-copy Metal buffer wrapping the entire mmap'd model file.
 * GPU reads weights/norms directly from unified memory via offset. */
static void *g_mmap_buf = NULL;
static const uint8_t *g_mmap_base = NULL;
static size_t g_mmap_len = 0;

/* Grow-on-demand scratch buffers for mutable per-dispatch data */
static void *g_scratch_x = NULL;
static void *g_scratch_xq = NULL;
static void *g_scratch_scale = NULL;
static void *g_scratch_xnorm = NULL;
static void *g_scratch_out = NULL;
static size_t g_scratch_x_cap = 0;
static size_t g_scratch_xq_cap = 0;
static size_t g_scratch_scale_cap = 0;
static size_t g_scratch_xnorm_cap = 0;
static size_t g_scratch_out_cap = 0;

/* ── Helpers ─────────────────────────────────────────────────────── */

#ifndef MIN
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#endif

/* Ensure scratch buffer is at least `needed` bytes; grow if necessary.
 * Returns false if Metal allocation fails (caller should fall back to CPU). */
static bool ensure_scratch(void **buf, size_t *cap, size_t needed)
{
    if (*cap >= needed)
        return true;
    void *new_buf = OC(void *, (void *, SEL, NSUInteger, NSUInteger))(
        g_device, sel("newBufferWithLength:options:"), (NSUInteger) needed,
        (NSUInteger) MTL_RESOURCE_STORAGE_MODE_SHARED);
    if (!new_buf)
        return false;
    release(*buf);
    *buf = new_buf;
    *cap = needed;
    return true;
}

/* Extract error description string (for diagnostics). */
static const char *error_string(void *error)
{
    if (!error)
        return "(unknown)";
    void *desc = OC(void *, (void *, SEL))(error, sel("localizedDescription"));
    if (!desc)
        return "(unknown)";
    return (const char *) OC(const char *, (void *, SEL))(desc,
                                                          sel("UTF8String"));
}

/* ── Public API ──────────────────────────────────────────────────── */

bool bm_metal_init(void)
{
    void *pool = objc_autoreleasePoolPush();

    g_device = MTLCreateSystemDefaultDevice();
    if (!g_device) {
        fprintf(stderr, "[METAL] No Metal device found\n");
        goto fail;
    }

    g_queue = OC(void *, (void *, SEL))(g_device, sel("newCommandQueue"));
    if (!g_queue) {
        fprintf(stderr, "[METAL] Failed to create command queue\n");
        goto fail;
    }

    /* Compile shaders from embedded source */
    void *ns_alloc = OC(void *, (void *, SEL))(cls(NSString), sel("alloc"));
    void *source =
        OC(void *, (void *, SEL, const void *, NSUInteger, NSUInteger))(
            ns_alloc, sel("initWithBytes:length:encoding:"),
            (const void *) src_metal_bm_shaders_metal,
            (NSUInteger) src_metal_bm_shaders_metal_len,
            (NSUInteger) NS_UTF8_STRING_ENCODING);

    void *opts_alloc =
        OC(void *, (void *, SEL))(cls(MTLCompileOptions), sel("alloc"));
    void *opts = OC(void *, (void *, SEL))(opts_alloc, sel("init"));

    if (__builtin_available(macOS 15.0, *)) {
        OC(void, (void *, SEL, NSUInteger))(opts, sel("setMathMode:"),
                                            (NSUInteger) MTL_MATH_MODE_FAST);
    } else {
        OC(void, (void *, SEL, bool) )(opts, sel("setFastMathEnabled:"), true);
    }

    void *error = NULL;
    void *library = OC(void *, (void *, SEL, void *, void *, void **) )(
        g_device, sel("newLibraryWithSource:options:error:"), source, opts,
        &error);
    release(source);
    release(opts);

    if (!library) {
        fprintf(stderr, "[METAL] Shader compilation failed: %s\n",
                error_string(error));
        goto fail;
    }

    /* Create compute pipelines */
    void *rms_fn = OC(void *, (void *, SEL, void *) )(
        library, sel("newFunctionWithName:"), nsstr("rms_norm_quantize"));
    void *bl_fn = OC(void *, (void *, SEL, void *) )(
        library, sel("newFunctionWithName:"), nsstr("bitlinear_batch"));
    void *resid_fn = OC(void *, (void *, SEL, void *) )(
        library, sel("newFunctionWithName:"), nsstr("residual_add"));
    release(library);

    if (!rms_fn || !bl_fn || !resid_fn) {
        fprintf(stderr, "[METAL] Failed to find kernel functions\n");
        release(rms_fn);
        release(bl_fn);
        release(resid_fn);
        goto fail;
    }

    error = NULL;
    g_rms_norm_quantize_pipeline = OC(void *, (void *, SEL, void *, void **) )(
        g_device, sel("newComputePipelineStateWithFunction:error:"), rms_fn,
        &error);
    if (!g_rms_norm_quantize_pipeline) {
        fprintf(stderr, "[METAL] RMS norm pipeline failed: %s\n",
                error_string(error));
        release(rms_fn);
        release(bl_fn);
        release(resid_fn);
        goto fail;
    }

    error = NULL;
    g_bitlinear_batch_pipeline = OC(void *, (void *, SEL, void *, void **) )(
        g_device, sel("newComputePipelineStateWithFunction:error:"), bl_fn,
        &error);
    if (!g_bitlinear_batch_pipeline) {
        fprintf(stderr, "[METAL] BitLinear pipeline failed: %s\n",
                error_string(error));
        release(rms_fn);
        release(bl_fn);
        release(resid_fn);
        goto fail;
    }

    error = NULL;
    g_residual_add_pipeline = OC(void *, (void *, SEL, void *, void **) )(
        g_device, sel("newComputePipelineStateWithFunction:error:"), resid_fn,
        &error);
    release(rms_fn);
    release(bl_fn);
    release(resid_fn);

    if (!g_residual_add_pipeline) {
        fprintf(stderr, "[METAL] Residual add pipeline failed: %s\n",
                error_string(error));
        goto fail;
    }

    g_metal_ready = true;
    void *dev_name = OC(void *, (void *, SEL))(g_device, sel("name"));
    const char *name = (const char *) OC(const char *, (void *, SEL))(
        dev_name, sel("UTF8String"));
    fprintf(stderr, "[METAL] Initialized: %s\n", name);

    objc_autoreleasePoolPop(pool);
    return true;

fail:
    bm_metal_cleanup();
    objc_autoreleasePoolPop(pool);
    return false;
}

bool bm_metal_available(void)
{
    return g_metal_ready;
}

bool bm_metal_set_mmap(const void *base, size_t size)
{
    if (!g_metal_ready || !base || size == 0)
        return false;

    pthread_mutex_lock(&g_metal_mutex);

    /* Release previous mmap buffer if replacing */
    if (g_mmap_buf) {
        release(g_mmap_buf);
        g_mmap_buf = NULL;
        g_mmap_base = NULL;
        g_mmap_len = 0;
    }

    /* Page-align length upward (mmap base is already page-aligned) */
    long page = getpagesize();
    size_t aligned_len = (size + (size_t) page - 1) & ~((size_t) page - 1);

    /* Create zero-copy Metal buffer wrapping the mmap'd region.
     * Apple Silicon unified memory: GPU reads these pages directly,
     * no copy, no extra allocation.  Deallocator is NULL because
     * the mmap lifecycle is managed by model.c (munmap in model_free). */
    g_mmap_buf = OC(void *,
                    (void *, SEL, void *, NSUInteger, NSUInteger, void *) )(
        g_device, sel("newBufferWithBytesNoCopy:length:options:deallocator:"),
        (void *) base, (NSUInteger) aligned_len,
        (NSUInteger) MTL_RESOURCE_STORAGE_MODE_SHARED, NULL);

    if (!g_mmap_buf) {
        fprintf(stderr, "[METAL] Failed to create zero-copy mmap buffer\n");
        pthread_mutex_unlock(&g_metal_mutex);
        return false;
    }

    g_mmap_base = (const uint8_t *) base;
    g_mmap_len = aligned_len;

    fprintf(
        stderr,
        "[METAL] Zero-copy mmap buffer: %zu bytes (page-aligned from %zu)\n",
        aligned_len, size);

    pthread_mutex_unlock(&g_metal_mutex);
    return true;
}

void bm_metal_bitlinear_forward_batch(const float *x_batch,
                                      int n_tokens,
                                      int n,
                                      const uint8_t *packed_data,
                                      int rows,
                                      int cols,
                                      float w_scale,
                                      const float *norm_weight,
                                      float *out_batch,
                                      float *x_norm_buf,
                                      int8_t *x_quant_batch,
                                      int quant_stride)
{
    void *pool = objc_autoreleasePoolPush();

    if (!g_metal_ready)
        goto done;

    pthread_mutex_lock(&g_metal_mutex);

    (void) x_norm_buf;    /* GPU uses its own scratch */
    (void) x_quant_batch; /* GPU uses its own scratch */

    /* Sanity check dimensions */
    if (n_tokens <= 0 || n <= 0 || rows <= 0 || cols <= 0 || quant_stride < n)
        goto done_locked;

    /* cols must be multiple of 16 for coalesced uint reads in shader */
    if (cols % 16 != 0) {
        fprintf(stderr, "[METAL] cols=%d not multiple of 16\n", cols);
        goto done_locked;
    }

    {
        int out_dim = rows;

        /* Compute offsets into the zero-copy mmap buffer */
        if (!g_mmap_buf || !g_mmap_base) {
            fprintf(stderr, "[METAL] No mmap buffer registered\n");
            memset(out_batch, 0, (size_t) n_tokens * out_dim * sizeof(float));
            goto done_locked;
        }

        /* Overflow-safe bounds check using ptrdiff_t */
        const uint8_t *w_ptr = (const uint8_t *) packed_data;
        const uint8_t *n_ptr = (const uint8_t *) norm_weight;
        const uint8_t *mmap_end = g_mmap_base + g_mmap_len;

        if (w_ptr < g_mmap_base || n_ptr < g_mmap_base || w_ptr >= mmap_end ||
            n_ptr >= mmap_end) {
            fprintf(stderr, "[METAL] Pointer outside mmap region\n");
            memset(out_batch, 0, (size_t) n_tokens * out_dim * sizeof(float));
            goto done_locked;
        }

        NSUInteger w_off = (NSUInteger) (w_ptr - g_mmap_base);
        NSUInteger n_off = (NSUInteger) (n_ptr - g_mmap_base);

        int packed_stride = (cols + 3) / 4;
        size_t weight_bytes = (size_t) rows * packed_stride;
        size_t norm_bytes = (size_t) n * sizeof(float);
        size_t w_avail = (size_t) (mmap_end - w_ptr);
        size_t n_avail = (size_t) (mmap_end - n_ptr);

        if (weight_bytes > w_avail || norm_bytes > n_avail) {
            fprintf(stderr, "[METAL] Tensor data exceeds mmap region\n");
            memset(out_batch, 0, (size_t) n_tokens * out_dim * sizeof(float));
            goto done_locked;
        }

        /* Ensure scratch buffers are large enough */
        size_t x_need = (size_t) n_tokens * n * sizeof(float);
        size_t xq_need = (size_t) n_tokens * quant_stride * sizeof(int8_t);
        size_t scale_need = (size_t) n_tokens * sizeof(float);
        size_t xnorm_need = sizeof(float); /* shader ignores x_norm_buf */
        size_t out_need = (size_t) n_tokens * out_dim * sizeof(float);

        if (!ensure_scratch(&g_scratch_x, &g_scratch_x_cap, x_need) ||
            !ensure_scratch(&g_scratch_xq, &g_scratch_xq_cap, xq_need) ||
            !ensure_scratch(&g_scratch_scale, &g_scratch_scale_cap,
                            scale_need) ||
            !ensure_scratch(&g_scratch_xnorm, &g_scratch_xnorm_cap,
                            xnorm_need) ||
            !ensure_scratch(&g_scratch_out, &g_scratch_out_cap, out_need)) {
            fprintf(stderr,
                    "[METAL] Scratch allocation failed, output zeroed\n");
            memset(out_batch, 0, (size_t) n_tokens * out_dim * sizeof(float));
            goto done_locked;
        }

        /* Copy mutable input activations into scratch */
        void *x_contents =
            OC(void *, (void *, SEL))(g_scratch_x, sel("contents"));
        memcpy(x_contents, x_batch, x_need);

        void *cmd = OC(void *, (void *, SEL))(g_queue, sel("commandBuffer"));

        /* Kernel 1: RMS norm + quantize */
        {
            void *enc =
                OC(void *, (void *, SEL))(cmd, sel("computeCommandEncoder"));
            OC(void, (void *, SEL, void *) )(enc,
                                             sel("setComputePipelineState:"),
                                             g_rms_norm_quantize_pipeline);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_scratch_x,
                (NSUInteger) 0, (NSUInteger) 0);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_mmap_buf, n_off,
                (NSUInteger) 1);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_scratch_xq,
                (NSUInteger) 0, (NSUInteger) 2);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_scratch_scale,
                (NSUInteger) 0, (NSUInteger) 3);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_scratch_xnorm,
                (NSUInteger) 0, (NSUInteger) 4);
            OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
                enc, sel("setBytes:length:atIndex:"), &n,
                (NSUInteger) sizeof(int), (NSUInteger) 5);
            OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
                enc, sel("setBytes:length:atIndex:"), &quant_stride,
                (NSUInteger) sizeof(int), (NSUInteger) 6);

            NSUInteger tg_size =
                MIN((NSUInteger) n, OC(NSUInteger, (void *, SEL))(
                                        g_rms_norm_quantize_pipeline,
                                        sel("maxTotalThreadsPerThreadgroup")));
            NSUInteger po2 = 1;
            while (po2 * 2 <= tg_size)
                po2 *= 2;
            tg_size = po2;

            /* Shared memory: one float per SIMD group for cross-group reduction
             */
            NSUInteger n_simd_groups = (tg_size + 31) / 32;
            OC(void, (void *, SEL, NSUInteger, NSUInteger))(
                enc, sel("setThreadgroupMemoryLength:atIndex:"),
                (NSUInteger) (n_simd_groups * sizeof(float)), (NSUInteger) 0);

            MTLSize grid = {(NSUInteger) n_tokens, 1, 1};
            MTLSize tg = {tg_size, 1, 1};
            OC(void, (void *, SEL, MTLSize, MTLSize))(
                enc, sel("dispatchThreadgroups:threadsPerThreadgroup:"), grid,
                tg);
            OC(void, (void *, SEL))(enc, sel("endEncoding"));
        }

        /* Kernel 2: Direct ternary bitlinear dot product */
        {
            void *enc =
                OC(void *, (void *, SEL))(cmd, sel("computeCommandEncoder"));
            OC(void, (void *, SEL, void *) )(enc,
                                             sel("setComputePipelineState:"),
                                             g_bitlinear_batch_pipeline);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_scratch_xq,
                (NSUInteger) 0, (NSUInteger) 0);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_scratch_scale,
                (NSUInteger) 0, (NSUInteger) 1);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_mmap_buf, w_off,
                (NSUInteger) 2);
            OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
                enc, sel("setBuffer:offset:atIndex:"), g_scratch_out,
                (NSUInteger) 0, (NSUInteger) 3);
            OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
                enc, sel("setBytes:length:atIndex:"), &rows,
                (NSUInteger) sizeof(int), (NSUInteger) 4);
            OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
                enc, sel("setBytes:length:atIndex:"), &cols,
                (NSUInteger) sizeof(int), (NSUInteger) 5);
            OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
                enc, sel("setBytes:length:atIndex:"), &w_scale,
                (NSUInteger) sizeof(float), (NSUInteger) 6);
            OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
                enc, sel("setBytes:length:atIndex:"), &quant_stride,
                (NSUInteger) sizeof(int), (NSUInteger) 7);
            OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
                enc, sel("setBytes:length:atIndex:"), &out_dim,
                (NSUInteger) sizeof(int), (NSUInteger) 8);

            NSUInteger tg_size = 1024;
            NSUInteger max_tg = OC(NSUInteger, (void *, SEL))(
                g_bitlinear_batch_pipeline,
                sel("maxTotalThreadsPerThreadgroup"));
            if (tg_size > max_tg)
                tg_size = max_tg;

            /* rows_per_tg derived from actual TG size (matches shader) */
            int rows_per_tg = (int) (tg_size / 32);
            int n_row_groups = (rows + rows_per_tg - 1) / rows_per_tg;

            /* Shared memory: activation cache (cols bytes) */
            NSUInteger shared_mem = (NSUInteger) cols;
            OC(void, (void *, SEL, NSUInteger, NSUInteger))(
                enc, sel("setThreadgroupMemoryLength:atIndex:"), shared_mem,
                (NSUInteger) 0);

            MTLSize grid = {(NSUInteger) n_row_groups, (NSUInteger) n_tokens,
                            1};
            MTLSize tg = {tg_size, 1, 1};
            OC(void, (void *, SEL, MTLSize, MTLSize))(
                enc, sel("dispatchThreadgroups:threadsPerThreadgroup:"), grid,
                tg);
            OC(void, (void *, SEL))(enc, sel("endEncoding"));
        }

        OC(void, (void *, SEL))(cmd, sel("commit"));
        OC(void, (void *, SEL))(cmd, sel("waitUntilCompleted"));

        NSUInteger status = OC(NSUInteger, (void *, SEL))(cmd, sel("status"));
        void *cmd_error = OC(void *, (void *, SEL))(cmd, sel("error"));

        if (status != MTL_CMD_BUF_STATUS_COMPLETED || cmd_error) {
            fprintf(stderr, "[METAL] Command buffer error: %s\n",
                    error_string(cmd_error));
            memset(out_batch, 0, (size_t) n_tokens * out_dim * sizeof(float));
        } else {
            void *out_contents =
                OC(void *, (void *, SEL))(g_scratch_out, sel("contents"));
            memcpy(out_batch, out_contents,
                   (size_t) n_tokens * out_dim * sizeof(float));
        }
    }

done_locked:
    pthread_mutex_unlock(&g_metal_mutex);
done:
    objc_autoreleasePoolPop(pool);
}

void bm_metal_cleanup(void)
{
    void *pool = objc_autoreleasePoolPush();

    /* Release zero-copy mmap buffer */
    release(g_mmap_buf);
    g_mmap_buf = NULL;
    g_mmap_base = NULL;
    g_mmap_len = 0;

    /* Release scratch buffers */
#define RELEASE_SCRATCH(buf, cap) \
    do {                          \
        release(buf);             \
        buf = NULL;               \
        cap = 0;                  \
    } while (0)
    RELEASE_SCRATCH(g_scratch_x, g_scratch_x_cap);
    RELEASE_SCRATCH(g_scratch_xq, g_scratch_xq_cap);
    RELEASE_SCRATCH(g_scratch_scale, g_scratch_scale_cap);
    RELEASE_SCRATCH(g_scratch_xnorm, g_scratch_xnorm_cap);
    RELEASE_SCRATCH(g_scratch_out, g_scratch_out_cap);
#undef RELEASE_SCRATCH

    release(g_rms_norm_quantize_pipeline);
    g_rms_norm_quantize_pipeline = NULL;
    release(g_bitlinear_batch_pipeline);
    g_bitlinear_batch_pipeline = NULL;
    release(g_residual_add_pipeline);
    g_residual_add_pipeline = NULL;
    release(g_queue);
    g_queue = NULL;
    release(g_device);
    g_device = NULL;

    g_metal_ready = false;
    fprintf(stderr, "[METAL] Cleaned up\n");

    objc_autoreleasePoolPop(pool);
}

/* ── Batch API ───────────────────────────────────────────────────── */

struct bm_metal_batch_ctx {
    void *cmd_buf;
    void *enc;
    void *buf_x;
    void *buf_proj;
    void *buf_y;
    void *buf_out;
    void *buf_xq;
    void *buf_scale;
    void *buf_xnorm;
    int n_tokens;
    int d_model;
    int max_proj;
    int d_inner;
    int quant_stride;
};

static void *alloc_shared_buf(size_t size)
{
    if (size == 0)
        return NULL;
    return OC(void *, (void *, SEL, NSUInteger, NSUInteger))(
        g_device, sel("newBufferWithLength:options:"), (NSUInteger) size,
        (NSUInteger) MTL_RESOURCE_STORAGE_MODE_SHARED);
}

bm_metal_batch_ctx_t *bm_metal_batch_begin(int n_tokens,
                                           int d_model,
                                           int max_proj,
                                           int d_inner,
                                           int quant_stride)
{
    if (!g_metal_ready)
        return NULL;
    pthread_mutex_lock(&g_metal_mutex);

    bm_metal_batch_ctx_t *ctx = calloc(1, sizeof(bm_metal_batch_ctx_t));
    if (!ctx) {
        pthread_mutex_unlock(&g_metal_mutex);
        return NULL;
    }

    ctx->n_tokens = n_tokens;
    ctx->d_model = d_model;
    ctx->max_proj = max_proj;
    ctx->d_inner = d_inner;
    ctx->quant_stride = quant_stride;

    /* Allocate persistent shared buffers */
    ctx->buf_x = alloc_shared_buf((size_t) n_tokens * d_model * sizeof(float));
    ctx->buf_proj =
        alloc_shared_buf((size_t) n_tokens * max_proj * sizeof(float));
    ctx->buf_y = alloc_shared_buf((size_t) n_tokens * d_inner * sizeof(float));
    ctx->buf_out =
        alloc_shared_buf((size_t) n_tokens * d_model * sizeof(float));

    /* Scratch buffers for quantization */
    ctx->buf_xq =
        alloc_shared_buf((size_t) n_tokens * quant_stride * sizeof(int8_t));
    ctx->buf_scale = alloc_shared_buf((size_t) n_tokens * sizeof(float));
    ctx->buf_xnorm =
        alloc_shared_buf(sizeof(float)); /* shader ignores x_norm_buf */

    if (!ctx->buf_x || !ctx->buf_proj || !ctx->buf_y || !ctx->buf_out ||
        !ctx->buf_xq || !ctx->buf_scale || !ctx->buf_xnorm) {
        bm_metal_batch_end(ctx); /* Handles cleanup */
        return NULL;
    }

    /* Start first command buffer */
    ctx->cmd_buf = OC(void *, (void *, SEL))(g_queue, sel("commandBuffer"));
    if (!ctx->cmd_buf) {
        bm_metal_batch_end(ctx);
        return NULL;
    }

    /* We don't create encoder yet; created on demand to switch pipelines */
    return ctx;
}

float *bm_metal_batch_ptr(bm_metal_batch_ctx_t *ctx, int buf_id)
{
    if (!ctx)
        return NULL;
    void *buf = NULL;
    switch (buf_id) {
    case BM_BUF_X:
        buf = ctx->buf_x;
        break;
    case BM_BUF_PROJ:
        buf = ctx->buf_proj;
        break;
    case BM_BUF_Y:
        buf = ctx->buf_y;
        break;
    case BM_BUF_OUT:
        buf = ctx->buf_out;
        break;
    default:
        return NULL;
    }
    return buf ? OC(float *, (void *, SEL))(buf, sel("contents")) : NULL;
}

static void ensure_encoder(bm_metal_batch_ctx_t *ctx, void *pipeline)
{
    /* Always start a new encoder to ensure memory consistency between kernels
     */
    if (ctx->enc) {
        OC(void, (void *, SEL))(ctx->enc, sel("endEncoding"));
        ctx->enc = NULL;
    }

    ctx->enc =
        OC(void *, (void *, SEL))(ctx->cmd_buf, sel("computeCommandEncoder"));
    OC(void, (void *, SEL, void *) )(ctx->enc, sel("setComputePipelineState:"),
                                     pipeline);
}

bool bm_metal_encode_bitlinear(bm_metal_batch_ctx_t *ctx,
                               int src_id,
                               int input_dim,
                               const uint8_t *packed_data,
                               int rows,
                               int cols,
                               float w_scale,
                               const float *norm_weight,
                               int dst_id)
{
    if (!ctx || !packed_data)
        return false;

    void *src_buf = (src_id == BM_BUF_X)   ? ctx->buf_x
                    : (src_id == BM_BUF_Y) ? ctx->buf_y
                                           : NULL;
    void *dst_buf = (dst_id == BM_BUF_PROJ)  ? ctx->buf_proj
                    : (dst_id == BM_BUF_OUT) ? ctx->buf_out
                                             : NULL;

    if (!src_buf || !dst_buf)
        return false;

    /* cols must be multiple of 16 for coalesced uint reads in shader */
    if (cols % 16 != 0) {
        fprintf(stderr, "[METAL] encode: cols=%d not multiple of 16\n", cols);
        return false;
    }

    /* Resolve mmap pointers */
    if (!g_mmap_buf || !g_mmap_base)
        return false;

    /* Overflow-safe bounds check using pointer arithmetic */
    const uint8_t *w_ptr = (const uint8_t *) packed_data;
    const uint8_t *n_ptr = (const uint8_t *) norm_weight;
    const uint8_t *mmap_end = g_mmap_base + g_mmap_len;

    if (w_ptr < g_mmap_base || n_ptr < g_mmap_base || w_ptr >= mmap_end ||
        n_ptr >= mmap_end) {
        fprintf(stderr, "[METAL] encode: pointer outside mmap region\n");
        return false;
    }

    NSUInteger w_off = (NSUInteger) (w_ptr - g_mmap_base);
    NSUInteger n_off = (NSUInteger) (n_ptr - g_mmap_base);

    int packed_stride = (cols + 3) / 4;
    size_t weight_bytes = (size_t) rows * packed_stride;
    size_t norm_bytes = (size_t) input_dim * sizeof(float);
    size_t w_avail = (size_t) (mmap_end - w_ptr);
    size_t n_avail = (size_t) (mmap_end - n_ptr);

    if (weight_bytes > w_avail || norm_bytes > n_avail) {
        fprintf(stderr, "[METAL] encode: tensor data exceeds mmap region\n");
        return false;
    }

    /* Kernel 1: RMS Norm + Quantize */
    ensure_encoder(ctx, g_rms_norm_quantize_pipeline);

    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), src_buf, 0, 0);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), g_mmap_buf, n_off, 1);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), ctx->buf_xq, 0, 2);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), ctx->buf_scale, 0, 3);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), ctx->buf_xnorm, 0, 4);

    int n = input_dim;
    int qs = ctx->quant_stride;
    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &n, sizeof(int), 5);
    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &qs, sizeof(int), 6);

    /* Clamp TG size to pipeline maximum */
    NSUInteger rms_tg = 1024;
    NSUInteger rms_max = OC(NSUInteger, (void *, SEL))(
        g_rms_norm_quantize_pipeline, sel("maxTotalThreadsPerThreadgroup"));
    if (rms_tg > rms_max)
        rms_tg = rms_max;
    if ((NSUInteger) n < rms_tg) {
        rms_tg = 1;
        while (rms_tg * 2 <= (NSUInteger) n)
            rms_tg *= 2;
    }

    /* Shared memory: one float per SIMD group for cross-group reduction */
    NSUInteger n_simd_groups = (rms_tg + 31) / 32;
    OC(void, (void *, SEL, NSUInteger, NSUInteger))(
        ctx->enc, sel("setThreadgroupMemoryLength:atIndex:"),
        n_simd_groups * sizeof(float), 0);

    MTLSize grid1 = {(NSUInteger) ctx->n_tokens, 1, 1};
    MTLSize tg1 = {rms_tg, 1, 1};
    OC(void, (void *, SEL, MTLSize, MTLSize))(
        ctx->enc, sel("dispatchThreadgroups:threadsPerThreadgroup:"), grid1,
        tg1);

    /* Kernel 2: BitLinear */
    ensure_encoder(ctx, g_bitlinear_batch_pipeline);

    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), ctx->buf_xq, 0, 0);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), ctx->buf_scale, 0, 1);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), g_mmap_buf, w_off, 2);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), dst_buf, 0, 3);

    int r = rows;
    int c = cols;
    int out_dim = rows;

    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &r, sizeof(int), 4);
    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &c, sizeof(int), 5);
    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &w_scale, sizeof(float), 6);
    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &qs, sizeof(int), 7);
    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &out_dim, sizeof(int), 8);

    OC(void, (void *, SEL, NSUInteger, NSUInteger))(
        ctx->enc, sel("setThreadgroupMemoryLength:atIndex:"), (NSUInteger) c,
        0);

    /* Clamp TG size to pipeline maximum */
    NSUInteger bl_tg = 1024;
    NSUInteger bl_max = OC(NSUInteger, (void *, SEL))(
        g_bitlinear_batch_pipeline, sel("maxTotalThreadsPerThreadgroup"));
    if (bl_tg > bl_max)
        bl_tg = bl_max;

    /* rows_per_tg derived from actual TG size (matches shader) */
    int rows_per_tg = (int) (bl_tg / 32);
    int n_row_groups = (r + rows_per_tg - 1) / rows_per_tg;

    MTLSize grid2 = {(NSUInteger) n_row_groups, (NSUInteger) ctx->n_tokens, 1};
    MTLSize tg2 = {bl_tg, 1, 1};
    OC(void, (void *, SEL, MTLSize, MTLSize))(
        ctx->enc, sel("dispatchThreadgroups:threadsPerThreadgroup:"), grid2,
        tg2);

    return true;
}

void bm_metal_encode_residual(bm_metal_batch_ctx_t *ctx, int count)
{
    if (!ctx)
        return;

    /* x += out (float4 vectorized: each thread handles 4 elements) */
    ensure_encoder(ctx, g_residual_add_pipeline);

    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), ctx->buf_x, 0, 0);
    OC(void, (void *, SEL, void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBuffer:offset:atIndex:"), ctx->buf_out, 0, 1);

    int c = count;
    OC(void, (void *, SEL, const void *, NSUInteger, NSUInteger))(
        ctx->enc, sel("setBytes:length:atIndex:"), &c, sizeof(int), 2);

    /* Each thread handles 4 floats via float4 */
    NSUInteger n_threads = ((NSUInteger) count + 3) / 4;
    NSUInteger tg_size = 256;
    NSUInteger n_groups = (n_threads + tg_size - 1) / tg_size;

    MTLSize grid = {n_groups, 1, 1};
    MTLSize tg = {tg_size, 1, 1};
    OC(void, (void *, SEL, MTLSize, MTLSize))(
        ctx->enc, sel("dispatchThreadgroups:threadsPerThreadgroup:"), grid, tg);
}

void bm_metal_submit_and_wait(bm_metal_batch_ctx_t *ctx)
{
    if (!ctx || !ctx->cmd_buf)
        return;

    if (ctx->enc) {
        OC(void, (void *, SEL))(ctx->enc, sel("endEncoding"));
        ctx->enc = NULL;
    }

    OC(void, (void *, SEL))(ctx->cmd_buf, sel("commit"));
    OC(void, (void *, SEL))(ctx->cmd_buf, sel("waitUntilCompleted"));

    /* Check command buffer error status (mirrors standalone path) */
    NSUInteger status =
        OC(NSUInteger, (void *, SEL))(ctx->cmd_buf, sel("status"));
    void *cmd_error = OC(void *, (void *, SEL))(ctx->cmd_buf, sel("error"));
    if (status != MTL_CMD_BUF_STATUS_COMPLETED || cmd_error) {
        fprintf(stderr, "[METAL] Batch command buffer error: %s\n",
                error_string(cmd_error));
    }

    release(ctx->cmd_buf);

    /* Create next command buffer immediately */
    ctx->cmd_buf = OC(void *, (void *, SEL))(g_queue, sel("commandBuffer"));
}

void bm_metal_batch_end(bm_metal_batch_ctx_t *ctx)
{
    if (!ctx)
        return;

    if (ctx->enc) {
        OC(void, (void *, SEL))(ctx->enc, sel("endEncoding"));
        /* Encoder is autoreleased, do not release explicitly */
        ctx->enc = NULL;
    }

    if (ctx->cmd_buf) {
        /* If it wasn't committed, commit it? */
        /* OC(void, (void *, SEL))(ctx->cmd_buf, sel("commit")); */
        release(ctx->cmd_buf);
    }

    release(ctx->buf_x);
    release(ctx->buf_proj);
    release(ctx->buf_y);
    release(ctx->buf_out);
    release(ctx->buf_xq);
    release(ctx->buf_scale);
    release(ctx->buf_xnorm);

    free(ctx);
    pthread_mutex_unlock(&g_metal_mutex);
}

#else /* !HAS_METAL */

/* Stubs when Metal is not available */
#include "bm_metal.h"

bool bm_metal_init(void)
{
    return false;
}
bool bm_metal_available(void)
{
    return false;
}
bool bm_metal_set_mmap(const void *base, size_t size)
{
    (void) base;
    (void) size;
    return false;
}
void bm_metal_bitlinear_forward_batch(const float *x_batch,
                                      int n_tokens,
                                      int n,
                                      const uint8_t *packed_data,
                                      int rows,
                                      int cols,
                                      float w_scale,
                                      const float *norm_weight,
                                      float *out_batch,
                                      float *x_norm_buf,
                                      int8_t *x_quant_batch,
                                      int quant_stride)
{
    (void) x_batch;
    (void) n_tokens;
    (void) n;
    (void) packed_data;
    (void) rows;
    (void) cols;
    (void) w_scale;
    (void) norm_weight;
    (void) out_batch;
    (void) x_norm_buf;
    (void) x_quant_batch;
    (void) quant_stride;
}
void bm_metal_cleanup(void) {}

bm_metal_batch_ctx_t *bm_metal_batch_begin(int n_tokens,
                                           int d_model,
                                           int max_proj,
                                           int d_inner,
                                           int quant_stride)
{
    (void) n_tokens;
    (void) d_model;
    (void) max_proj;
    (void) d_inner;
    (void) quant_stride;
    return NULL;
}
float *bm_metal_batch_ptr(bm_metal_batch_ctx_t *ctx, int buf_id)
{
    (void) ctx;
    (void) buf_id;
    return NULL;
}
bool bm_metal_encode_bitlinear(bm_metal_batch_ctx_t *ctx,
                               int src_id,
                               int input_dim,
                               const uint8_t *packed_data,
                               int rows,
                               int cols,
                               float w_scale,
                               const float *norm_weight,
                               int dst_id)
{
    (void) ctx;
    (void) src_id;
    (void) input_dim;
    (void) packed_data;
    (void) rows;
    (void) cols;
    (void) w_scale;
    (void) norm_weight;
    (void) dst_id;
    return false;
}
void bm_metal_encode_residual(bm_metal_batch_ctx_t *ctx, int count)
{
    (void) ctx;
    (void) count;
}
void bm_metal_submit_and_wait(bm_metal_batch_ctx_t *ctx)
{
    (void) ctx;
}
void bm_metal_batch_end(bm_metal_batch_ctx_t *ctx)
{
    (void) ctx;
}

#endif /* HAS_METAL */
